# Generated by Django 5.0.4 on 2024-06-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('revenue1', models.IntegerField()),
                ('employees', models.CharField(max_length=200)),
                ('revenue2', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
                ('headquarter', models.CharField(max_length=200)),
            ],
        ),
    ]
